server:
  port: 5000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-client
    zipkin:
      base-url: http:/localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
  rabbitmq:
    host: locahost
    port: 5672
    username: admin
    password: 123456

zuul:
  routes:
    hiapi:
      path: /hiapi/**
      service-id: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      service-id: eureka-ribbon-client
    feiapi:
      path: /feiapi/**
      service-id: eureka-feign-client





