spring:
  application:
    name: service-turbine
server:
  port: 8769

turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-ribbon-client,eureka-feign-client
  cluster-name-expression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/